name: Youcon

google_analytics: UA-62253510-1

markdown: kramdown

# This flag means that event is still in progress but registration is closed
is_registration_open: true

# This flag means that event is in progress, otherwise need to transform to cooming soon page
is_in_progress: true

previous_events:
    - name: "2017"
      link: https://2017.youcon.ru
    - name: "2016"
      link: https://2016.youcon.ru
    - name: "2015"
      link: https://2015.youcon.ru
other_events:
    - name: "Хакатон"
      link: https://ottepel.youcon.ru
    - name: "Дюна"
      link: http://dune.youcon.ru

event_date: "13 октября 2018"
event_city: "Саратов"
event_location_name: "Саратовская Государственная Юридическая Академия" 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
